FROM alpine:latest
RUN apk add curl bash
ARG MUTAGEN_VERSION
ENV MUTAGEN_TUNNEL_HOST_VERSION=${MUTAGEN_VERSION}
ENV DEFAULT_MUTAGEN_TUNNEL_AGENT_VERSIONS=${MUTAGEN_VERSION}
COPY provision.sh provision.sh
RUN ./provision.sh
